spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/motorprodb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:motorprolevel}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.security.jwt.secret-key=${JWT_SECRET:46/Xxctu1XNdT6Xf+xRPY6UyvWDpjJQYi7OKLc2D/G5dcDU4ARr093Hatrjdg6k6CqmO+9WUU/y2G4cN+RWw7g==}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}
