spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:none}

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION:604800000}

# application.properties
google.client.id=370037172549-ovgss6jj25sqv9b321m3hfle8usl9um3.apps.googleusercontent.com

cors.allowed-origins=${CORS_ORIGINS}

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
server.forward-headers-strategy=native